spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/pay?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
server:
  port: 8888
  context-path: /pay

alipay:
  appId: 2016091200494104
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDrpP5HSWz0LZLKFtc31cNJY0aDQVBJyw4Uh6lv1r+xg+C+DbdMNPIGvuMSyb2i8Y7pBAS5k7nHAK+LUU0HzVHD6YG/ylrOOU0lFGuWHbCut7/YecQSxVsV5/Ve4ZCQX4+fjVG5hYfYs5hmzVey1VsOd1S8pVnLVjIFeq5VvulU/+hQ8UR11X+0dC0m6srjWv2B+9oBwxmEPNIaONecCQnQtiQZLzLSOFrs/0AosO0qrdM9Wpt/Y39ERnUtExet0FdWG4Vo3IMrxgIkHGVZUMAj7SzY1nCuRtG1C2DxKIHHhqvLeBk8+GQpffLJ/OYPJp2AF1/+qbfMFgKruJE6t3TfAgMBAAECggEANyY0RKbQkw0fb6CM2gpzW/eaBxoAGmUldHSTmRMfZgJBVPmMzo8NnbqLFliUw0/ZbHt+R5hlQEfOzcJHTu4klr9NmH9ZZS5P+b+ftlBYi2uBwL4uv13lBWl2KbCMzt0uld7TI6I2uua9YkHopnf8iZQwBr6EF2yi5Flj97lojnWrCAbZHTuzyIiD1ELHfopM+3ApPQ248jng1WfLAzEyYFEFQ/0A74PD5XuwGB8S4+2quaNF9XEax83REkciN9reyxF+7GcJ3DuUj8GRxI+yvZuKmib8VE8c3kZAvXbliWrZ2Z1OZe9iVAU/7TIlK48w0KBW3UzWWdxC1RZOkK89IQKBgQD2ZWE9XxPkLZRQjB+wVzhecyBurF2wq6LZ3e5gjlqx1oZnSs0r9x9l0BFb3bbyB2YOJb+51R8ud9LXent1HFBlhfGtJmSEgQi6BZmYX/BJdj70ydeXZJFgdYCNkwWA/cRwK3KGLevymhlSc8oc7ZV+vTPAd3WdNvlYQcugOTRgeQKBgQD01FTS6a2YYpWMnEkOCnPyHVvbzsmNkPOlqZqKGP5mGwsopNGjTfvTWAVVF0hxdQ4LAQGJBrcCcBwCX6MCfUCtLro35fhf0XiJY/EIfZM27ponReGIN4Z9JGJ7+wi/sIyrHD9BwUYwRsvO7eob2sJq+TbiXPs6apuJLVHbwkqaFwKBgCFogZTGrXXE0FVTioBocxYrWfxnlpR70SrlMosZAicWxUaAF+2cJj+xxIjGOSX75tSIPcS+pumwCYB59P9eBXCehrRJfluQ+1PtqnPEnln3lHWwYHEAi82eYP3RL2/b+KSU34Rd+Z39Uu2hEYh2lkyG7ttr1yCn8YsL8MYau4VRAoGAVuS1ZlYBgsAai9k8JHuZQykgXRc7eb8kenuDmdfdEqgugbJdpTQcWJo46kZlM79zyHwG63cypO7dQgpndI630b9v4D8CtB9IRJrwBS9sfGaa1615qjrqxKeRPKeQJ1il1GUmHlRWcPPvifXuzQwLTKQ+0oBlugn0Qe+PygtfJukCgYB+GA0k2V1pK3Jn3Fpg7CHUBsbwKqdyq3R7qfivzuLaHuk+CzqPSdT5KcAkF6H2yxQpfMlj9TRLhglFvvihL9CtVA0bjpG4Ahwzty8DJC6xDfRRTbOM2R+q3DiyjVj+bflE4/GRu+dseRexR0Le2s+SruhF2kPCEiTHRmaJjkpxtg==
  charset: utf-8
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA66T+R0ls9C2SyhbXN9XDSWNGg0FQScsOFIepb9a/sYPgvg23TDTyBr7jEsm9ovGO6QQEuZO5xwCvi1FNB81Rw+mBv8pazjlNJRRrlh2wrre/2HnEEsVbFef1XuGQkF+Pn41RuYWH2LOYZs1XstVbDndUvKVZy1YyBXquVb7pVP/oUPFEddV/tHQtJurK41r9gfvaAcMZhDzSGjjXnAkJ0LYkGS8y0jha7P9AKLDtKq3TPVqbf2N/REZ1LRMXrdBXVhuFaNyDK8YCJBxlWVDAI+0s2NZwrkbRtQtg8SiBx4ary3gZPPhkKX3yyfzmDyadgBdf/qm3zBYCq7iROrd03wIDAQAB
  returnUrl: http://www.baidu.com
  notifyUrl: http://domain.com/CallBack/notify_url.jsp